# Generated by Django 4.2.6 on 2023-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment_anime",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment_manga",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
