# Generated by Django 4.2.6 on 2023-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bee", "0002_alter_comment_anime_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment_anime",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment_manga",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
