# Generated by Django 4.2.6 on 2023-11-04 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bee", "0003_alter_comment_anime_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction_anime",
            unique_together={("anime_id", "user", "reaction_type")},
        ),
    ]
